version: "1"

services:
  elasticpot:
    build: .
    container_name: vikrant-elasticpot
    restart: always
    ports:
      - "9200:9200"
    read_only: true
    volumes:
      - ../../data/elasticpot/log:/opt/elasticpot/log
