version: '1'

services:
  honeytrap:
    build: .
    container_name: vikrant-honeytrap
    restart: always
    tmpfs:
     - /tmp/honeytrap:uid=2000,gid=2000
    network_mode: "host"
    cap_add:
     - NET_ADMIN
    read_only: true
    volumes:
     - ../../data/honeytrap/attacks:/opt/honeytrap/var/attacks
     - ../../data/honeytrap/downloads:/opt/honeytrap/var/downloads
     - ../../data/honeytrap/log:/opt/honeytrap/var/log